### ISSUE TITLE
Is this plugin going forward?

### ISSUE THREAD

**Issue by marceloverdijk** [brunoborges/azure-gradle-plugins#5]
Hi @brunoborges Is this plugin being maintained? Would be great to finally deploy Gradle builds easily to Azure...

**Comment by brunoborges** [comment]
It is, but under the official Microsoft organization. Unfortunately though, I don't have dates yet for when we will release it.

**Comment by marceloverdijk** [comment]
Thx for the feedback and good to hear official support is being worked on. Maybe good to add a note about this in the README?
